// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIf_0daPbthIDKGG4J864-f0rrRCNvSM4',
    appId: '1:115838115955:web:e457ac68c7cd24cd1b8a06',
    messagingSenderId: '115838115955',
    projectId: 'demofire-5b972',
    authDomain: 'demofire-5b972.firebaseapp.com',
    storageBucket: 'demofire-5b972.appspot.com',
    measurementId: 'G-VF32NEY3JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXE-tM_0jjyIkRUOSqdnwCCZCSbORU28',
    appId: '1:115838115955:android:3fb6733cda84a6931b8a06',
    messagingSenderId: '115838115955',
    projectId: 'demofire-5b972',
    storageBucket: 'demofire-5b972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPIu-UI1u6Nokg1vlRFhvlMgZUcYMYrs',
    appId: '1:115838115955:ios:091d8f0b4292f78a1b8a06',
    messagingSenderId: '115838115955',
    projectId: 'demofire-5b972',
    storageBucket: 'demofire-5b972.appspot.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxPIu-UI1u6Nokg1vlRFhvlMgZUcYMYrs',
    appId: '1:115838115955:ios:091d8f0b4292f78a1b8a06',
    messagingSenderId: '115838115955',
    projectId: 'demofire-5b972',
    storageBucket: 'demofire-5b972.appspot.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIf_0daPbthIDKGG4J864-f0rrRCNvSM4',
    appId: '1:115838115955:web:8dcc527423df09b31b8a06',
    messagingSenderId: '115838115955',
    projectId: 'demofire-5b972',
    authDomain: 'demofire-5b972.firebaseapp.com',
    storageBucket: 'demofire-5b972.appspot.com',
    measurementId: 'G-BY5JCCNT6C',
  );
}
